"use client";

const GUIDE_STEPS = [
  {
    number: "1",
    title: "Choose the correct worksheet",
    text: "Use Operation Medals for combat-operation recommendations. Use Service Medals for service, contribution, leadership, and Service Unit Award recommendations. Both worksheets support individual medals and unit awards.",
  },
  {
    number: "2",
    title: "Select the award first",
    text: "Choose the medal or unit award before filling out the rest of the worksheet. Any required Action Scope, Action Character, or award-specific fields will appear automatically. Review Award Criteria & Guidance before continuing.",
  },
  {
    number: "3",
    title: "Complete the details and recipients",
    text: "Enter the recommendation details requested for the selected award, then choose each recipient from the eligible roster. Do not type a name and leave it unmatched. Service Unit Awards include a Bulk Add Recipients tool for large groups.",
  },
  {
    number: "4",
    title: "Write the narrative",
    text: "Write the recommendation narrative in your own words and follow the sentence guidance shown for the selected award. Some Service Medal narratives continue a sentence starter generated by the aid. Individual recommendations have a 1,400-character soft cap and 1,600-character hard cap. Unit awards have a 1,600-character soft cap and 1,800-character hard cap.",
  },
  {
    number: "5",
    title: "Generate and review",
    text: "Select Generate Recommendation and review the completed citation, recipient names, validation checks, and warnings. Correct any failed checks before moving forward. Warnings deserve review even when they do not block generation.",
  },
  {
    number: "6",
    title: "Copy, preview, and submit",
    text: "Use the Copy buttons for the ticket title and forum BBCode, then open the Medal Recommendation ticket. Preview the forum post and proofread the complete recommendation before submitting. Do not copy text directly from the recommendation preview.",
  },
];

const AID_HANDLES = [
  "Required citation opening and closing language",
  "Recipient and MILPACS formatting",
  "Ticket-title and forum BBCode structure",
  "Award-specific fields and basic validation",
];

const USER_HANDLES = [
  "Selecting the correct award and confirming eligibility",
  "Writing an accurate and professional narrative",
  "Verifying names, dates, locations, units, and facts",
  "Final proofreading, judgment, and submission",
];

function ResponsibilityCard({ title, items }) {
  return (
    <article className="border border-[#363636] bg-[#151515] p-5">
      <h2 className="text-lg font-semibold text-[#ebc729]">{title}</h2>
      <ul className="mt-3 space-y-2 text-sm leading-6 text-[#b8b8b8]">
        {items.map((item) => (
          <li key={item} className="flex gap-2">
            <span className="mt-[1px] text-[#ebc729]">•</span>
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </article>
  );
}

export default function HowToUseView({
  onBack,
  onOpenOperation,
  onOpenService,
}) {
  return (
    <section className="py-4">
      <div className="mb-7">
        <button
          type="button"
          onClick={onBack}
          className="mb-3 text-sm font-semibold text-[#aaa] transition hover:text-[#ebc729]"
        >
          ← Back to Home
        </button>

        <h1 className="text-3xl font-bold text-[#ebc729]">How To Use</h1>

        <p className="mt-2 max-w-4xl text-sm leading-6 text-[#b0b0b0]">
          The Medal Recommendation Aid is a formatting and submission aid. It
          helps assemble the required citation language, roster formatting,
          validation checks, ticket title, and forum BBCode. It does not decide
          whether an award is deserved or replace the recommender&apos;s
          responsibility for the recommendation.
        </p>
      </div>

      <div className="mb-8 grid gap-4 md:grid-cols-2">
        <ResponsibilityCard title="What the aid handles" items={AID_HANDLES} />
        <ResponsibilityCard
          title="What the recommender handles"
          items={USER_HANDLES}
        />
      </div>

      <div className="mb-4">
        <h2 className="text-xl font-semibold text-[#ebc729]">
          Recommended Workflow
        </h2>
        <p className="mt-1 text-sm leading-6 text-[#929292]">
          Work through the worksheet from top to bottom. Selecting the award
          first allows the aid to show only the fields and guidance that apply.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {GUIDE_STEPS.map((step) => (
          <article
            key={step.number}
            className="border border-[#363636] bg-[#151515] p-5"
          >
            <div className="mb-4 flex h-9 w-9 items-center justify-center border border-[#ebc729] font-bold text-[#ebc729]">
              {step.number}
            </div>

            <h3 className="text-lg font-semibold text-[#e5e5e5]">
              {step.title}
            </h3>

            <p className="mt-2 text-sm leading-6 text-[#b8b8b8]">{step.text}</p>
          </article>
        ))}
      </div>

      <div className="mt-8 border border-[#484848] bg-[#191919] p-5">
        <h2 className="text-lg font-semibold text-[#ebc729]">
          Before You Submit
        </h2>

        <p className="mt-2 max-w-5xl text-sm leading-6 text-[#b8b8b8]">
          Read the finished citation as if you were the reviewer receiving it.
          Make sure the award, recipient list, dates, units, operation or
          service details, and narrative are correct. The aid can catch many
          formatting problems, but it cannot verify whether the facts or award
          judgment are correct.
        </p>
      </div>

      <div className="mt-6 grid gap-3 sm:grid-cols-2">
        <button
          type="button"
          onClick={onOpenOperation}
          className="border border-[#555] bg-[#202020] px-5 py-4 font-semibold text-[#ddd] transition hover:border-[#ebc729] hover:text-[#ebc729]"
        >
          Open Operation Medals
        </button>

        <button
          type="button"
          onClick={onOpenService}
          className="border border-[#555] bg-[#202020] px-5 py-4 font-semibold text-[#ddd] transition hover:border-[#ebc729] hover:text-[#ebc729]"
        >
          Open Service Medals
        </button>
      </div>
    </section>
  );
}
